controller/contour/controller_test.go
controller/contour/finalizer_test.go
controller/contour/suite_test.go

Adds initial integration testing for the contour controller:
- Creates integration testing environment setup
- Covers api defaulting.
- Covers finalizing `contour`.

Adds Integration Testing

---

go.mod
go.sum

Removes unused stretchr/testify dep from `go.mod`.
/assign @jpeach @stevesloka

Removes unused stretchr/testify dep

---

README.md

Updates the readme to include developer on-boarding steps.
/cc @Miciah

Adds Developer Steps to Readme

---

api/v1alpha1/contour_types.go
config/crd/bases/operator.projectcontour.io_contours.yaml

This fixes #32.
Signed-off-by: James Peach <jpeach@vmware.com>

Enable the status subresource.

---

Makefile
README.md

Updates the readme and makefile for deploying and testing the operator.
/cc @Miciah 

Updates Readme and Makefile

---

.github/workflows/prbuild.yaml
.gitignore
Makefile
config/crd/bases/operator.projectcontour.io_contours.yaml
hack/install-kubernetes-toolchain.sh
hack/kind-dev-cluster.sh

ci: Add build + run tests on each PR from Github Actions

---

controller/contour/deployment.go

Updates Contour's deployment to create the pod security context from package `github.com/projectcontour/contour-operator/util`.
/cc @Miciah

Updates SecurityContext of Contour Deployment

---

Dockerfile

This should fix the failing Docker build.

Dockerfile: fix multiarch build

---

controller/contour/controller.go

Previously, `ensureContour()` was called twice for every reconciliation of a new `Contour`. This is because appending a finalizer modifies the object causing a reconciliation. This PR makes `ensureContour()` conditional based on the presence of the finalizer.
/assign @jpeach @stevesloka @skriss 
/cc @Miciah 

Refactors Controller Reconciler

---

config/crd/bases/operator.projectcontour.io_contours.yaml

Updates the Contour CRD based on `make test`.
/assign @stevesloka @skriss @jpeach 
/cc @Miciah 

Updates Contour CRD

---

docs/CONTRIBUTING.md

Updates the contrib guide to use the `check` target.
xref: https://github.com/projectcontour/contour-operator/issues/9
/assign @stevesloka @skriss @jpeach 
/cc @Miciah

Updates Make Target in Contrib Doc

---

api/v1alpha1/contour_types.go
config/crd/bases/operator.projectcontour.io_contours.yaml

Uppercases field names in Contour API documentation.
xref: https://github.com/projectcontour/contour-operator/pull/91

Uppercases API Field Names

---

Makefile
config/manager/kustomization.yaml
config/manager/manager.yaml
hack/release/make-release-tag.sh

Ports the Contour [final release](https://projectcontour.io/resources/release-process/#final-release) process to Contour Operator.
Fixes: https://github.com/projectcontour/contour-operator/issues/55
xref: https://github.com/projectcontour/contour-operator/issues/71
/assign @stevesloka @skriss @jpeach 
/cc @Miciah 

Adds Support for Release Automation

---

.codespell.skip
.github/workflows/prbuild.yaml
Makefile
api/v1alpha1/contour_types.go
config/crd/bases/operator.projectcontour.io_contours.yaml
controller/contour/job.go
hack/codespell.sh

- Ports Contour's `codespell` spell checking support to Contour Operator.
- Fixes spelling mistakes throughout the codebase caught by `codespell`.

Adds Codespell Support

---

RELEASE.md

Adds release documentation.
Fixes: https://github.com/projectcontour/contour-operator/issues/123

Adds Release Docs

---

test/e2e/operator_test.go
test/e2e/utils.go

Adds an e2e test to exercise `spec.namespace.name` and `spec.namespace.removeOnDeletion` fields of a `Contour`.

Adds Spec Namespace e2e Test

---

controller/contour/rbac.go
util/object.go

Signed-off-by: sheetalsingala <ssingala@redhat.com>
Fixes #139

Use Kubernetes networking v1

---

Makefile

When the build looks for an existing installation of controller-gen,
it can find one with a different version. This leads to spurious diffs
when the different version of controller-gen generates different output.
Better to use `go run` to run the versino that is pinned in the Go
modules. This means that everyone gets the same result.
Signed-off-by: James Peach <jpeach@vmware.com>

build: always use the pinned controller-gen

---

cmd/contour-operator.go
config/manager/manager.yaml
controller/contour/suite_test.go
examples/operator/operator.yaml

Match Contour change https://github.com/projectcontour/contour/pull/3245

Bump Envoy to 1.17.0

---

CODEOWNERS

add CODEOWNERS files to enable automatic PR requests

---

config/rbac/auth_proxy_client_clusterrole.yaml
examples/operator/operator.yaml

Updates the auth proxy ClusterRole to v1.
Fixes https://github.com/projectcontour/contour-operator/issues/156

Updates Auth Proxy ClusterRole to v1

---

config/crd/contour/01-crds.yaml
examples/operator/operator.yaml

Bumps projectcontour/contour CRDs in support of https://github.com/projectcontour/contour/pull/3267 and https://github.com/projectcontour/contour/pull/3251.

Bumps projectcontour/contour CRDs

---

config/crd/contour/01-crds.yaml
examples/operator/operator.yaml

Bumps HTTPProxy CRD due to https://github.com/projectcontour/contour/pull/3274.

Bumps HTTPProxy CRD

---

hack/release/make-release-tag.sh

Updates the release script to update versioned links in `README.md`.

Adds Readme Update to Release Script

---

config/crd/contour/01-crds.yaml
examples/operator/operator.yaml

Bumps the ExtensionService CRD due to https://github.com/projectcontour/contour/pull/3282.

Bumps ExtensionService CRD

---

examples/contour/contour.yaml
hack/kind-dev-cluster.sh
internal/equality/equality.go
internal/equality/equality_test.go
internal/object/object.go
internal/operator/config/config.go
internal/operator/controller/contour/controller.go
internal/operator/controller/contour/controller_test.go
internal/operator/controller/contour/daemonset.go
internal/operator/controller/contour/daemonset_test.go
internal/operator/controller/contour/deployment.go
internal/operator/controller/contour/deployment_test.go
internal/operator/controller/contour/service.go
internal/operator/controller/contour/service_test.go
internal/operator/controller/contour/validate.go
internal/operator/controller/contour/validate_test.go
internal/operator/suite_test.go
internal/slice/slice.go
test/e2e/operator_test.go
test/e2e/utils.go

Implements the Network Publishing API defined in https://github.com/projectcontour/contour-operator/pull/151.
Requires:
- https://github.com/projectcontour/contour-operator/pull/151
- https://github.com/projectcontour/contour-operator/pull/162

Implements Network Publishing API

---

internal/operator/controller/contour/configmap.go
internal/operator/controller/contour/configmap_test.go

Updates the Contour ConfigMap due to https://github.com/projectcontour/contour/pull/3292 and https://github.com/projectcontour/contour/pull/3316

Updates the Contour ConfigMap

---

design/gateway-api.md

Renames Service APIs design spec to -> Gateway API.

Renames Service APIs Design Spec

---

config/manager/manager.yaml
examples/operator/operator.yaml
internal/objects/clusterrole/cluster_role.go
internal/operator/config/config.go

- Updates Envoy image to 1.17.1
- Updates RBAC for get/list/watch of namespace resources.
xref: https://github.com/projectcontour/contour/pull/3402
xref:  https://github.com/projectcontour/contour/pull/3417

Updates Envoy Image and Adds Namespace RBAC

---

Makefile
hack/load-image.sh
hack/reset-image.sh
hack/verify-image.sh
internal/objects/clusterrole/cluster_role.go
internal/objects/clusterrolebinding/cluster_role_binding.go
internal/objects/configmap/configmap.go
internal/objects/configmap/configmap_test.go
internal/objects/contour/contour.go
internal/objects/daemonset/daemonset.go
internal/objects/deployment/deployment.go
internal/objects/gateway/gateway.go
internal/objects/job/job.go
internal/objects/namespace/namespace.go
internal/objects/rbac.go
internal/objects/role/role.go
internal/objects/rolebinding/role_binding.go
internal/objects/service/service.go
internal/objects/serviceaccount/service_account.go
internal/operator/controller/contour/controller.go
internal/operator/controller/gateway/controller.go
pkg/labels/labels.go
pkg/labels/labels_test.go

Adds support for configuring gateway name/namespace in the Contour ConfigMap.
Requires: https://github.com/projectcontour/contour-operator/pull/246
Fixes: #241

Adds Contour Gateway Config Support

---

Makefile

Updates `fmt` Make target to cover e2e tests.
xref: https://github.com/projectcontour/contour-operator/pull/269

Updates Gofmt to Cover e2e Tests

---

.github/workflows/prbuild.yaml
Makefile
test/e2e/operator_test.go
test/e2e/utils.go

To ensure test/e2e package is checked

Add e2e build tag to golangci-lint commands

---

config/crd/contour/01-crds.yaml
examples/operator/operator.yaml

This PR updates the projectcontour/contour CRD based on the changes from https://github.com/projectcontour/contour/pull/3522.

Bumps projectcontour/contour CRD

---

internal/operator/controller/contour/controller.go
internal/operator/controller/gateway/controller.go

Extracts some helper functions for processing the results of
"ensure" function calls to reduce duplication and improve
readability.

extract helpers to simplify ensure/ensureDeleted methods

---

README.md
config/manager/manager.yaml
examples/operator/operator.yaml
internal/operator/config/config.go

Updates to Contour v1.14.1 & Envoy v1.17.2

V1.14.1 Release Upgrade

---

internal/operator/config/config.go

See also https://github.com/projectcontour/contour/pull/3589

Bump Envoy to 1.18.2 for CVE fixes

---

internal/operator/suite_test.go

In suite_test.go, wraps Update(...) calls in Eventually(...)
to mitigate concurrent modification issues causing test flakes.
Closes #251.

internal/operator: tests: wrap updates in Eventually

---

internal/operator/operator.go

This patch uses rest mapper instead of `client.Get()` to verify
Gateway CRDs. It reduce API calls and is same method with Contour.
Fix https://github.com/projectcontour/contour-operator/issues/270

Use rest mapper instead of Get to verify Gateway CRDs

---

docs/CONTRIBUTING.md

Fix https://github.com/projectcontour/contour-operator/issues/307
/cc @skriss @danehans 

Add kubebuilder to Prerequisites in CONTRIBUTING.md

---

test/e2e/operator_test.go
test/e2e/utils.go

Adds an e2e upgrade test that performs the following:
- Sets the operator to the latest release to simulate the upgrade "from" release.
- Provisions a `Contour` using release "latest" and verifies e2e connectivity, no errors in operator logs, etc..
- Upgrades the operator to simulate the upgrade "to" release.
- Ensures the operator and Contour are using the updated image tag.
- Verifies post-upgrade e2e connectivity.
Partially fixes https://github.com/projectcontour/contour-operator/issues/142. Due to a) PR size and b) current Gateway API implementation under review, this PR does not include Gateway upgrade testing.

Adds e2e Upgrade Test

---

config/crd/contour/01-crds.yaml
examples/operator/operator.yaml

Update Contour CRDs to match latest

---

test/e2e/operator_test.go
test/e2e/utils.go

Adds support for running e2e tests against standard k8s clusters. This is required for testing features that kind does not support, i.e. AWS cloud internal load-balancer.
- Adds `isKindCluster()` to check whether the cluster under test was provisioned using kind. The func checks for the presence of the "kindnet" daemonset to make the determination.
- Adds `getWorkerNodeIP()` required to construct the test url for tests that use the "NodePortService" networking publishing type (specific to k8s clusters).
- Adds `labelWorkerNodes()` since kind does not label worker nodes with the standard "node-role.kubernetes.io/worker" label.
- Updates each test to use a unique namespace. This ensures the failure of one test does not affect other tests (running multiple Contour's in the same ns is not …

Updates e2e for non-kind clusters

---

.github/workflows/prbuild.yaml
hack/actions/install-kubernetes-toolchain.sh
hack/kind-dev-cluster.sh
internal/objects/gatewayclass/gatewayclass.go
test/e2e/operator_test.go
test/e2e/utils.go

Pulled out of https://github.com/projectcontour/contour-operator/pull/311 to remove the complication of a dependency bump

Test against k8s 1.21.0 in example and e2e tests

---

internal/operator/config/config.go

update Envoy to v1.18.3

---

internal/objects/gateway/gateway.go
pkg/validation/validation.go
pkg/validation/validation_test.go

Adds unit tests to cover this case
Removes some nil checks in internal code
Updates #337

GatewayClass with missing parametersRef or missing fields is validated

---

test/e2e/operator_test.go

Many failed CI jobs are related to wait function timeouts. This PR sets a 3-Minute timeout for all e2e `waitX()` functions to reduce test flakes.
cc: @skriss 

Sets a 3-Minute Timeout for All e2e Wait Functions

---

config/crd/contour/01-crds.yaml
examples/operator/operator.yaml

Bumps the Contour CRDs due to https://github.com/projectcontour/contour/pull/3661.

Bumps Contour CRDs

---

examples/operator/operator.yaml

Bumps the operator's example manifests due to https://github.com/projectcontour/contour-operator/pull/365.

Bumps Example Operator Manifest

---

.github/workflows/prbuild.yaml
hack/actions/install-kubernetes-toolchain.sh

See release notes:
https://github.com/kubernetes-sigs/kind/releases/tag/v0.11.1

Bump kind cli and images

---

docs/CONTRIBUTING.md

Updates Contrib Guide for Kubebuilder Changes

---

pkg/validation/validation.go
pkg/validation/validation_test.go

Fixes #240 by verifying the referenced ingress class exists.

Adds IngressClassName Validation

---

examples/contour/contour-aws-internal-lb.yaml

Adds an example contour custom resoruce object that would provision with
an internal-facing load balancer.

Add example contour deployment with internal-elb

---

.github/workflows/prbuild.yaml

the latter is only available on PRs

Use github.ref instead of github.head_ref

---

internal/config/config.go

update Envoy to 1.19.0

---

Makefile

Add specific packages to be checked for coverage

---

config/crd/contour/01-crds.yaml
examples/operator/operator.yaml

Pulls in updated projectcontour/contour CRD YAML
from https://github.com/projectcontour/contour/pull/3953.

update projectcontour/contour CRD YAML

---

internal/operator/operator_test.go

Fix operator test data race

---

Makefile
config/crd/contour/01-crds.yaml
examples/operator/operator.yaml
hack/actions/check-uncommitted-codegen.sh

Signed-off-by: Nick Young <ynick@vmware.com>

Update Contour CRDs

---

config/crd/contour/01-crds.yaml
examples/operator/operator.yaml

update projectcontour/contour CRDs

---

config/rbac/role.yaml
examples/operator/operator.yaml
internal/objects/clusterrole/cluster_role.go
internal/operator/operator.go

add ContourConfiguration RBAC

---

internal/objects/daemonset/daemonset.go
internal/objects/daemonset/daemonset_test.go

Updates Envoy DaemonSet to align with https://github.com/projectcontour/contour/pull/4084
Signed-off-by: Tero Saarni <tero.saarni@est.tech>

Added securityContext to run Envoy as non-root.

---

config/crd/contour/01-crds.yaml
examples/operator/operator.yaml

Syncs Contour CRDs from https://github.com/projectcontour/contour/pull/3707.

sync Contour CRDs

---

config/rbac/role.yaml
examples/operator/operator.yaml
internal/objects/clusterrole/cluster_role.go
internal/operator/operator.go

Changes from: https://github.com/projectcontour/contour/pull/4202

Update rbac for changes to leaderelection

---

config/crd/contour/01-crds.yaml
examples/operator/operator.yaml

update HTTPPRoxy CRD

---

.github/workflows/prbuild.yaml
Dockerfile

update Go version to 1.17.5

---

config/crd/gateway/01-crds.yaml
examples/operator/operator.yaml
go.mod
go.sum

update Gateway API to v0.4.1

---

test/e2e/operator_test.go

test/e2e: re-enable upgrade test

---

internal/objects/service/service.go

Minor refactor to simplify DesiredEnvoyService
function's code.

internal/objects: simplify DesiredEnvoyService code

---

internal/objects/clusterrole/cluster_role.go
internal/objects/rbac.go
internal/objects/role/role.go
internal/objects/role/role_test.go

Adds Contour Role and RoleBinding
See Controller PR: https://github.com/projectcontour/contour/pull/4204

Switch to Role for leaderelection resource RBAC

---

config/crd/contour/01-crds.yaml
examples/operator/operator.yaml

sync CRDs from Contour

---

internal/config/config.go

- update Envoy to v1.21.1 (#496)

Cherrypicks for v1.20.1

---

config/crd/contour/01-crds.yaml
examples/operator/operator.yaml

sync CRDs from projectcontour/contour

---

internal/operator/config.go

update Envoy to 1.22.0

---

.github/workflows/prbuild.yaml
Dockerfile

See release notes: https://go.dev/doc/devel/release#go1.18.minor

Bump Go to 1.18.1

---

go.mod
go.sum

update Gateway API to v0.4.3

---

.github/workflows/prbuild.yaml
internal/status/conditions.go
internal/status/conditions_test.go

fix lint issues

---

.github/workflows/prbuild.yaml
Dockerfile
Makefile
hack/golangci-lint.sh
internal/objects/namespace/namespace.go
tools/tools.go

Also bump golangci-lint to 1.48.0

Bump go to 1.19.0

---

internal/operator/config.go

update Envoy to v1.23.1

---

.github/workflows/prbuild.yaml

switch to GitHub Action codecov uploader

---

Makefile
config/crd/gateway/01-crds.yaml
examples/operator/operator.yaml
go.mod
go.sum

update to Gateway API v0.5.1

---

config/crd/contour/01-crds.yaml
examples/operator/operator.yaml
internal/operator/config.go

- sync CRDs
- update Envoy to v1.24.0

sync operator with projectcontour/contour

---

.github/workflows/prbuild.yaml

bump golangci-lint action to v3

---

config/crd/gateway/01-crds.yaml
examples/operator/operator.yaml
go.mod
go.sum

update to Gateway API v0.6.0

---

internal/operator/config.go

update Envoy to v1.25.0
