Makefile, api/v1alpha1/contour_types.go, config/crd/bases/operator.projectcontour.io_contours.yaml, config/samples/operator_v1alpha1_contour.yaml
- `Makefile`: Set v1 as the CRD version to support CRD defaulting.
`api/v1alpha1/contour_types.go`: Adds `spec.replicas` and `status.availableReplicas` fields to the Contour API type.
- `config/crd/bases/operator.projectcontour.io_contours.yaml`: Generated CRD updates from changes to `api/v1alpha1/contour_types.go`.
`config/samples/operator_v1alpha1_contour.yaml`: Removed example `foo` field. Note that `{}` is required since `spec` can not be null.
/assign @jpeach 
/cc @youngnick @Miciah
=> Adds replicas to Contour API type

util/retryableerror/retryableerror_test.go
Using `(*testing.T)Run()` to run named subtest removed a bit of test
boilerpplate, and makes it possible to run individual test cases.
Signed-off-by: James Peach <jpeach@vmware.com>
=> Convert tests to subtest style.

Dockerfile, config/default/kustomization.yaml, config/manager/manager.yaml, config/rbac/role.yaml, controller/contour/controller.go
Previously, the `docker-build` make target would fail due to the `util/` directory not being copied at build time. The PR also fixes the `make deploy` target so the operator can run in-cluster and reconcile `Contour` objects.
/cc @jpeach @Miciah
=> Fixes Operator Build and Deployment Make Targets

controller/contour/controller.go, controller/contour/finalizer.go, controller/contour/namespace.go
Using named fields makes it easier to find where fields are used, which
helps refactoring and code readability.
Signed-off-by: James Peach <jpeach@vmware.com>
=> Hoist the controller client into a named field.

.gitignore
Adds the generated `bin` directory to `.gitignore`.
/cc @jpeach @stevesloka
=> Ignore the bin Directory

controller/contour/controller.go, controller/contour/finalizer.go, controller/contour/namespace.go, util/retryableerror/retryableerror_test.go
Wraps errors with `%w` instead of `%v`. In Go 1.13, `fmt.Errorf()` supports a new `%w` verb. When this verb is present, the error returned by `fmt.Errorf()` will have an Unwrap method returning the argument of `%w`, which must be an error. In all other ways, `%w` is identical to `%v`.
/cc @Miciah
=> Wraps Errors with %w Verb

api/v1alpha1/contour_types.go, config/crd/bases/operator.projectcontour.io_contours.yaml
Since the value of `Replicas` is being defaulted, the field should be required instead of optional.
/cc @Miciah
=> Updates Replicas Field Requirement in Contour API

api/v1alpha1/contour_types.go, config/crd/bases/operator.projectcontour.io_contours.yaml
Updates the `RemoveOnDeletion` API field docs to include "kube-system" as a namespace that will __not__ be removed even when a `true` value is provided.
See https://github.com/projectcontour/contour-operator/pull/25#discussion_r489467685 for additional background.
/assign @stevesloka 
/cc @Miciah
=> Updates Docs for RemoveOnDeletion API Field

controller/contour/namespace.go
Previously, `ensureNamespace()` was returning an error during the 2nd pass of contour object reconciliation. This is due to a race between the Contour object being updated by ensureFinalizer() and the namespace create operation. This PR updates the control flow of the function to fix the error case for create and delete operations.
__Before:__
```
2020-09-02T12:33:22.826-0700  INFO  controllers.Contour reconciling {"request": "default/contour-sample"}
2020-09-02T12:33:22.838-0700  INFO  controllers.Contour added finalizer to contour  {"finalizer": "contour.operator.projectcontour.io/finalizer", "namespace": "default", "name": "contour-sample"}
2020-09-02T12:33:22.948-0700  INFO  controllers.Contour created namespace {"name": "projectcontour"}
2020-09-02T12:33:22.948-0700  DEBUG controller …
```
=> Protects ensureNamespace() Against Race with Contour

controller/contour/controller.go, controller/contour/namespace.go
Implements the Namespace API added in https://github.com/projectcontour/contour-operator/pull/20. Updates `ensureNamespace()` and `ensureNamespaceRemoved()` to use a `Contour` object instead of a namespace string as a parameter. Updates `ensureNamespaceRemoved()` to only remove the namespace if RemoveOnDeletion is unset and the namespace does not match a name in namespaceBlacklist.
Requires PR https://github.com/projectcontour/contour-operator/pull/24
/cc @Miciah
=> Implements Contour Namespace API

config/rbac/role.yaml, controller/contour/configmap.go, controller/contour/configmap_test.go, controller/contour/controller.go
Adds support for managing Contour's ConfigMap.
Fixes https://github.com/projectcontour/contour-operator/issues/38
@jpeach @skriss @stevesloka @Miciah PTAL
=> Adds Contour ConfigMap Support

controller/contour/rbac.go
Import ordering kept getting rearranged after running `make test`. This PR updates the RBAC import ordering to make `make test` happy.
/cc @Miciah
=> Fixes RBAC Import Ordering

config/rbac/role.yaml, controller/contour/controller.go, controller/contour/job.go, controller/contour/job_test.go, go.mod, util/equality/equality.go, util/equality/equality_test.go, util/object.go
Adds support for managing the Contour certgen `Job`.
Fixes https://github.com/projectcontour/contour-operator/issues/39
@jpeach @skriss @stevesloka @Miciah PTAL
=> Adds Certgen Job Support

api/v1alpha1/contour_types.go, controller/contour/configmap.go, controller/contour/controller.go, controller/contour/job.go, util/equality/equality.go, util/equality/equality_test.go
Previously, `JobConfigChanged()` would always update the existing cert-gen `Job` due to API defaults not being set by `DesiredJob()`.
- `api/v1alpha1/contour_types.go`: `OwningContourLabel` constant is moved from `controller/contour/controller.go ` so it can be used by packages throughout the operator.
- `controller/contour/job.go`: Adds fields that are defaulted by the api server.
- `util/equality/equality.go`: Updates the equality comparison of `JobConfigChanged()` to only compare managed `Job` fields. Reorders the returned values of `JobConfigChanged()`to be idiomatic.
- `util/equality/equality_test.go`: Updates tests based on `util/equality/equality.go` changes.
/cc @Miciah
=> Fixes Job Equality Comparison

cmd/contour-operator.go, config/rbac/role.yaml, controller/contour/controller.go, controller/contour/controller_test.go, controller/contour/deployment.go, controller/contour/deployment_test.go, controller/contour/job_test.go, go.mod, go.sum, util/equality/equality.go, util/equality/equality_test.go
Adds support for managing the Contour `Deployment` based on [this](https://github.com/projectcontour/contour/blob/main/examples/contour/03-contour.yaml) reference.
Fixes https://github.com/projectcontour/contour-operator/issues/37
/cc @jpeach @skriss @stevesloka @Miciah
=> Adds Contour Deployment Support

cmd/contour-operator.go, config/rbac/role.yaml, controller/contour/configmap_test.go, controller/contour/controller.go, controller/contour/controller_test.go, controller/contour/daemonset.go, controller/contour/daemonset_test.go, controller/contour/deployment.go, controller/contour/deployment_test.go, controller/contour/finalizer_test.go, controller/contour/job.go, controller/contour/job_test.go, controller/contour/suite_test.go, util/equality/equality.go, util/equality/equality_test.go
Adds support for managing Envoy through a `DaemonSet` resource.
Fixes https://github.com/projectcontour/contour-operator/issues/40
/assign @jpeach @stevesloka @skriss 
/cc @Miciah
=> Adds Envoy DaemonSet Support

controller/contour/deployment.go, controller/contour/deployment_test.go, util/slice/slice.go
Updates copyright headers that were missed by https://github.com/projectcontour/contour-operator/pull/48.
xref: https://github.com/projectcontour/contour-operator/issues/11
/assign @jpeach @stevesloka
=> Adds Missing Contour Copyright Headers

cmd/contour-operator.go
Updates the default Envoy version to 1.16.0.
Fixes https://github.com/projectcontour/contour-operator/issues/56
/assign @stevesloka @skriss @jpeach 
/cc @Miciah
=> Bumps Envoy Version to 1.16.0

controller/contour/job.go, controller/contour/job_test.go, util/equality/equality_test.go
Previously, the `Job` name was derived from `contour.Name` . This PR aligns the `Job` name with upstream until multiple `Contour` instances per namespace are [supported](https://github.com/projectcontour/contour-operator/issues/18).
/cc @stevesloka @skriss 
=> Updates Job Name

controller/contour/rbac.go, go.mod
Previously, no policy rules existed for the contour service account to manage CRDs. This PR aligns the operator's RBAC management with [upstream](https://github.com/projectcontour/contour/blob/main/examples/contour/02-role-contour.yaml).
/cc @stevesloka @skriss 
=> Adds CRD to RBAC Policy Rules

controller/contour/controller.go, controller/contour/service.go, controller/contour/service_test.go, util/equality/equality.go, util/equality/equality_test.go
Adds support for managing the Contour and Envoy `Service`.
Fixes https://github.com/projectcontour/contour-operator/issues/51
Requires https://github.com/projectcontour/contour-operator/pull/65 for port variables.
/cc @Miciah 
=> Adds Contour and Envoy Service Support

controller/contour/configmap.go, controller/contour/configmap_test.go, controller/contour/deployment.go
Previously, the `ConfigMap` name was derived from `contour.Name` . This PR aligns the `ConfigMap` name with upstream until multiple `Contour` instances per namespace are [supported](https://github.com/projectcontour/contour-operator/issues/18).
=> Updates ConfigMap Name

controller/contour/daemonset.go, controller/contour/deployment.go, controller/contour/job.go, controller/contour/rbac.go, util/equality/equality_test.go
Previously, the `Deployment` name was derived from `contour.Name + "contour"` . This PR does the following:
- Aligns the `Deployment` name with upstream until multiple `Contour` instances per namespace are [supported](https://github.com/projectcontour/contour-operator/issues/18).
- Updates container port definitions and other port references to use port variables.
- Updates RBAC variable naming
- Fixes equality test to reference both liveness and readiness probes from the correct container name (shutdown-manager).
Requires https://github.com/projectcontour/contour-operator/pull/63 for `contourCfgMapName` variable.
/cc @stevesloka @skriss 
=> Updates Deployment Name

config/rbac/role.yaml, controller/contour/controller.go
Previously, running the operator in-cluster would result in [these errors](https://gist.githubusercontent.com/danehans/bc09eca3b00858ee933f1b751287ee8f/raw/931b60adddec169eb1a5b33517ae653dc2870a1c/02_run_in_cluster). This PR updates RBAC for the resources managed by the operator. 
/cc @Miciah 
=> Updates Operator RBAC Configuration

controller/contour/daemonset.go, controller/contour/daemonset_test.go, util/equality/equality_test.go
Previously, the `DaemonSet` name was derived from `contour.Name + "envoy"` . This PR does the following:
- Aligns the `DaemonSet` name with upstream until multiple `Contour` instances per namespace are [supported](https://github.com/projectcontour/contour-operator/issues/18).
- Moves the `ReadinessProbe` from the shutdown-manager container to the envoy container (where it belongs).
- Updates container port definitions and other port references to use port variables.
- Sets `readOnly: false` for Envoy's config volume (as it should be).
- Updates unit tests as needed.
Requires https://github.com/projectcontour/contour-operator/pull/65 for port variables.
/cc @stevesloka @skriss 
=> Updates DaemonSet Name

controller/contour/deployment.go
This PR fixes the `containerPort` reference of the Contour `Deployment` to correctly reference metrics and debug TCP port numbers.
Fixes https://github.com/projectcontour/contour-operator/issues/73
/assign @stevesloka @jpeach @skriss @Miciah 
xref: https://github.com/projectcontour/contour/pull/3061
=> Updates Container Ports in Contour Deployment

Makefile, README.md, config/manager/kustomization.yaml
- Updates default image to `docker.io/projectcontour/contour-operator:latest`.
- Updates readme to remove the `docker-build` and `docker-push` targets as only the `deploy` target is needed.
- Adds verification step to readme.
/assign @jpeach @stevesloka @skriss 
/cc @Miciah 
=> Updates Readme and Makefile

.github/workflows/build_main.yaml, Dockerfile, Makefile
This commit adds a multiarch image build for the `main` branch only, with
the same mechanisms as mainline Contour. This should give us am64 and arm64
images.
Signed-off-by: Nick Young <ynick@vmware.com>
=> Add a multiarch image build for `main`

go.mod, go.sum
Marks `github.com/go-logr/zapr` as an indirect dependency.
=> Mark Zapr as an Indirect Dependency

Makefile, config/manager/kustomization.yaml
#83 updated the image variable from `IMG` to `IMAGE` but the `deploy` target still references the old variable. This PR updates the `deploy` target to use `IMAGE` and removes `latest` from the manager kind customization since it's unneeded (`image` of manager is already specified as latest).
/assign @youngnick @jpeach @stevesloka
=> Fixes Makefile Image Reference

.github/workflows/prbuild.yaml
For each PR or merge to :main, run the golangci-lint task against the codebase.
=> ci: Add golangci-lint step to build & test github actions

controller/contour/daemonset.go
https://github.com/projectcontour/contour/pull/3074 has caused `Envoy` not to start:
```
h:101] StreamListeners gRPC config stream closed: 12, unknown service envoy.api.v2.ListenerDiscoveryService
[2020-11-02 19:06:20.735][1][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] StreamClusters gRPC config stream closed: 12, unknown service envoy.api.v2.ClusterDiscoveryService
```
This PR adds support for the `--xds-resource-version` Envoy flag that was introduced in the above PR.
/assign @jpeach 
/cc @stevesloka @Miciah
=> Adds xDS Resource Version to Envoy DaemonSet

.github/workflows/prbuild.yaml
"The Error: The add-path command is deprecated and will be disabled soon. Please upgrade to using Environment Files."
=> Updates how paths are added when installing deps in Github Actions.

controller/contour/namespace.go, controller/contour/rbac.go
- Removes unused RBAC methods.
- Updates functions to use the provided `context` instead of creating a `context.TODO()`.
xref: https://github.com/projectcontour/contour-operator/pull/93
/assign @stevesloka @jpeach 
/cc @Miciah 
=> Fixes Linting Issues

Makefile
#83 added docker-related make targets. Similar targets existed from kubebuilder bootstrapping. This PR removes docker targets created from kubebuilder bootstrapping and calls the `test` target before building the docker image.
/assign @stevesloka @jpeach 
/cc @youngnick @Miciah
=> Updates Makefile Docker Targets

Makefile, config/manager/kustomization.yaml
Previously the make `deploy` target was using tag `latest` by default. This PR updates `config/manager/kustomization.yaml` and the `deploy` target and to be consistent with other targets by defaulting to the `main` tag.
/assign @stevesloka @jpeach 
/cc @Miciah 
=> Updates Makefile & Kustomize for Tag main

config/rbac/role.yaml, controller/contour/controller.go
Updates operator RBAC to allow get|list|watch verbs for endpoints and all verbs for services. __Note:__ The operator requires all verbs for services since it manages contour/envoy services. Get|List|Watch verbs for endpoints is required so the operator can delegate to the [contour ClusterRole](https://github.com/projectcontour/contour/blob/main/examples/contour/02-role-contour.yaml#L20-L27). 
Closes #78 
/cc @Miciah 
=> Updates Operator RBAC Rules

.gitignore, .golangci.yml, Makefile, config/crd/bases/operator.projectcontour.io_contours.yaml, controller/contour/configmap.go, controller/contour/configmap_test.go, controller/contour/controller_test.go, controller/contour/finalizer_test.go, controller/contour/rbac.go, controller/contour/service.go, hack/golangci-lint.sh, util/equality/equality.go, util/equality/equality_test.go
Adds a `lint-golint` task in the Makefile to run golangci-lint on the codebase. Also adds `check` task to run tests & the linting in one step while developing.
The second commit in the PR fixes up the errors found from running the linting task. 
@danehans there are a bunch of methods that aren't used that I hated to just delete, so they are commented out right now. If we don't need them then we should just remove. =)
Closes #92
=> makefile: Add golangci-lint make task

README.md, docs/CONTRIBUTING.md
Adds contributor documentation and updates `README.md` to reference the contributor documentation. This PR borrows heavily from Contour's [contributors guide](https://github.com/projectcontour/contour/blob/main/CONTRIBUTING.md).
/assign @stevesloka @jpeach @skriss 
/cc @Miciah 
=> Adds Contributor Documentation

api/v1alpha1/contour_types.go, config/crd/bases/operator.projectcontour.io_contours.yaml
Previously, spec and status were using the godocs of `ContourSpec` and `ContourStatus`. This may cause confusion when using `kubectl explain` to understand the details of a Contour resource. For example:
```
$ kubectl explain contours.spec
KIND:     Contour
VERSION:  operator.projectcontour.io/v1alpha1
RESOURCE: spec <Object>
DESCRIPTION:
ContourSpec defines the desired state of Contour.
...
```
`DESCRIPTION` should refer to "Spec" instead of "ContourSpec".
=> Adds Godocs for Contour Spec and Status

Makefile
Adds the Contour CRDs to the `uninstall` make target. This is needed since the `install` make target installs these CRDs.
=> Updates Makefile Uninstall Target

config/manager/manager.yaml
This PR fixes a bug introduced by https://github.com/projectcontour/contour-operator/pull/116 that causes the operator use image `contour` instead of `contour-operator`.
=> Fixes Image References in Operator Deployment

Makefile, README.md, config/crd/contour/01-crds.yaml, config/crd/kustomization.yaml, config/default/kustomization.yaml, config/manager/kustomization.yaml, config/manager/manager.yaml, config/namespace/kustomization.yaml, config/namespace/namespace.yaml, docs/CONTRIBUTING.md, examples/README.md, examples/contour/contour.yaml, examples/operator/operator.yaml, hack/generate-contour-crds.sh
- `Makefile`: Refactors Makefile to support the example manifest workflow.
- `README.md`: Updates readme to support the example manifest workflow.
- `config/crd/contour/01-crds.yaml`: Contains the Contour CRDs, i.e. HTTPProxy, and is maintained by the `manifests` make target.
- `config/crd/kustomization.yaml`: Includes the Contour CRDs in kustomize builds.
- `config/manager/manager.yaml`: Removes the operator namesapce from the operator's deployment.
- `config/default/kustomization.yaml `: Includes the Operator's namespace in kustomize builds.
- `config/namespace/namespace.yaml `: The Operator's namespace spec previsouly in `config/manager/manager.yaml`.
- `docs/CONTRIBUTING.md`: Refactors CONTRIBUTING.md to support the example manifest workflow.
- `examples/README.md`: Adds a simple …
=> Adds Support for Example Deployment Workflow

README.md
Links to the operator and example CR manifests need to be from `raw.githubusercontent`:
```
$ kubectl apply -f https://github.com/projectcontour/contour-operator/tree/main/examples/operator/operator.yaml
error: error parsing https://github.com/projectcontour/contour-operator/tree/main/examples/operator/operator.yaml: error converting YAML to JSON: yaml: line 90: mapping values are not allowed in this context
```
=> Fixes Links in Readme

README.md, config/default/kustomization.yaml, config/default/manager_auth_proxy_patch.yaml, config/default/manager_webhook_patch.yaml, config/default/webhookcainjection_patch.yaml, config/manager/manager.yaml, config/namespace/namespace.yaml, config/rbac/auth_proxy_client_clusterrole.yaml, config/rbac/auth_proxy_role.yaml, config/rbac/auth_proxy_role_binding.yaml, config/rbac/auth_proxy_service.yaml, config/rbac/contour_viewer_role.yaml, config/rbac/leader_election_role.yaml, config/rbac/leader_election_role_binding.yaml, config/rbac/role_binding.yaml, examples/operator/operator.yaml
Previously, kustomize would add the `contour-operator` prefix to resources, including the `contour-operator` namespace. This is not an issue with newer versions of kustomize that do not use the `namePrefix` with namespaces, but is with `v3.5.4` used by `install-kubernetes-toolchain.sh`. This PR removes `namePrefix` and renames config resources based on the `contour-operator` naming scheme.
xref: https://github.com/projectcontour/contour-operator/pull/130
=> Removes contour-operator Config Prefix

Makefile, config/rbac/role.yaml, examples/operator/operator.yaml
Although ClusterRoleBinding changed ClusterRole to `contour-operator`  in [this PR](https://github.com/projectcontour/contour-operator/pull/132/files#diff-35b14df70621e3a3c1ad38cb23c6439d87b9b0742ab3b10ad7238d8d47a3f72eL8),
the ClusterRole still has the old name `manager-role`.
Due to this, operator always fails to start.
This patch fixes it by changing the name to `contour-operator` from `manager-role`.
/cc @danehans @jpeach
=> Fix role name manager-role to contour-operator

.github/workflows/prbuild.yaml
Adds the `deploy` make target to the `test-linux` GitHub Actions job.
Requires: https://github.com/projectcontour/contour-operator/pull/120
=> Adds the Deploy Target to CI

Makefile, docs/CONTRIBUTING.md
https://github.com/projectcontour/contour-operator/pull/83 from @youngnick added the `VERSION` variable for building/pushing the operator image. However, the `VERSION` variable already existed. This PR:
- Removes the variable duplication.
- Updates the `run` make target to install the necessary CRDs before locally running the operator.
- Updates the contrib guide accordingly.
=> Fixes Makefile VERSION variable

examples/operator/operator.yaml
Regenerates the Operator example deployment due to https://github.com/projectcontour/contour-operator/pull/137.
=> Regenerates Operator Example

.github/workflows/prbuild.yaml, Makefile, docs/CONTRIBUTING.md, test/e2e/operator_test.go, test/e2e/utils.go, util/object.go
Adds e2e tests that include:
- `.github/workflows/prbuild.yaml`: Adds the `test-e2e` make target to action `test`.
- `Makefile`: Adds `test-e2e` target to run e2e tests.
- `docs/CONTRIBUTING.md`: Updates testing references in contrib docs.
- `test/e2e/operator_test.go`: Adds e2e tests.
- `test/e2e/utils.go`: Adds e2e test utility functions.
- `util/object.go`: Adds functions for creating new objects used by e2e tests.
Requires: https://github.com/projectcontour/contour-operator/pull/132
=> Adds e2e Testing

.github/workflows/prbuild.yaml
Splits the `test`  and `test-e2e` tests into separate CI jobs.
=> Splits Test Jobs

cmd/contour-operator.go
Adds info-level logging for the contour/envoy images used by the operator.
Fixes: https://github.com/projectcontour/contour-operator/issues/109
=> Adds Contour/Envoy Image Logging

.github/workflows/prbuild.yaml, Makefile, hack/test-examples.sh
- Adds a CI job for testing the example manifests.
- Fixes the test name of `test-linux` and `test-e2e-linux` CI jobs.
=> Adds Example Manifests CI Job

cmd/contour-operator.go, config/manager/manager.yaml, controller/contour/suite_test.go, examples/operator/operator.yaml
https://github.com/projectcontour/contour/pull/3151 updated the envoy image to 1.16.1. This PR does the same for the operator.
=> Upgrades Envoy Image to v1.16.1

Makefile, config/manager/kustomization.yaml, config/manager/manager.yaml, docs/CONTRIBUTING.md, hack/deploy-operator.sh, hack/release/make-release-tag.sh, hack/reset-image-refs.sh, hack/verify-image-refs.sh
Previously, using the `IMAGE` variable would not cause the image to be set in the operator's deployment. This PR allows kustomize to update the operator's image in `config/manager/manager.yaml` through the make `deploy` target.
Fixes a regression introduced by https://github.com/projectcontour/contour-operator/pull/129 and https://github.com/projectcontour/contour-operator/pull/132.
=> Fixes Operator Image Dev/Release Workflow

README.md, config/crd/bases/operator.projectcontour.io_contours.yaml
This patch adds `additionalPrinterColumns` for Contour custom resrouce.
After this patch, contour custom resource shows the status like below:
```
$ kubectl get contours.operator.projectcontour.io
NAME             READY   REASON
contour-sample   False   ContourUnavailable
$ kubectl get contours.operator.projectcontour.io
NAME             READY   REASON
contour-sample   True    ContourAvailable
```
/cc @danehans @skriss
=> Add additional status column for Contour custom resource

README.md, api/v1alpha1/contour_types.go, config/crd/bases/operator.projectcontour.io_contours.yaml, config/crd/contour/01-crds.yaml, examples/operator/operator.yaml
- Regenerates the Contour CRD based on controller-gen v0.4.0.
- Implements the changes from PR #154 based on kubebuilder additional printer columns [documentation](https://book.kubebuilder.io/reference/generating-crd.html?highlight=print#additional-printer-columns).
- Regenerates the example operator manifest due to the CRD changes (including PR #154 CRD changes).
cc: @nak3 
=> Updates Contour CRD

config/manager/manager.yaml, examples/operator/operator.yaml
The operator is being `OOMKilled` on occasion:
```
$ kubectl get po -n contour-operator
NAME                                READY   STATUS      RESTARTS   AGE
contour-operator-5d5986cdf7-6zxjf   1/2     OOMKilled   1          6m19s
```
Testing indicates the operator requires at least 35m of memory:
```
Every 2.0s: kubectl top pod contour-operator-5bdcfdf5df-j9vfx --containers --namespace contour-operator        daneyons-MBP: Wed Dec  9 11:12:13 2020
POD                                 NAME               CPU(cores)   MEMORY(bytes)
contour-operator-5bdcfdf5df-j9vfx   contour-operator   1m           35Mi
contour-operator-5bdcfdf5df-j9vfx   kube-rbac-proxy    0m           9Mi
```
This PR increases requested and limits of operator container memory resources.
Signed-off-by: Daneyon Hansen …
=> Bumps Operator Resources

config/manager/manager.yaml, examples/operator/operator.yaml
https://github.com/projectcontour/contour-operator/pull/157 bumped the operator's resources. The operator is still occasionally being OOMKillled due to resource limits. This PR removes the resource limits and bumps the requested memory.
=> Remove Resource Limits and Bump Memory

cmd/contour-operator.go, config/crd/contour/01-crds.yaml, config/manager/manager.yaml, controller/contour/suite_test.go, examples/operator/operator.yaml
Bumps Envoy to v1.16.2 and Contour CRD due to https://github.com/projectcontour/contour/pull/3203.
=> Bumps Contour CRD and Envoy Version

cmd/contour-operator.go, go.mod, go.sum, util/parse.go, util/parse_test.go
Validates `contour-image` and `envoy-image` command-line flags.
Fixes: https://github.com/projectcontour/contour-operator/issues/41
=> Validates Image Command-line Flags

hack/load-image.sh, hack/release/make-release-tag.sh
https://github.com/projectcontour/contour-operator/pull/162 set `imagePullPolicy: Always` for the operator. This PR updates the value to `IfNotPresent` (default) to be consistent with Contour [examples](https://github.com/projectcontour/contour/tree/main/examples/contour).
=> Sets the Operator Image Pull Policy to IfNotPresent

README.md
Manually updates the Readme versioned links from `main` to `v1.11.0`. This will be automated for future releases when https://github.com/projectcontour/contour-operator/pull/167 merges.
=> Updates Versioned Links in Readme

hack/test-example.sh
In some instances, it takes longer than 50-seconds for an instance of Contour to become available and begin serving traffic. This PR increases the number of test curl's to 100 to prevent test flakes.
=> Updates Examples Test Timeout

docs/CONTRIBUTING.md
Running e2e tests require the operator image to be loaded onto the kind cluster. This PR updates the contributors guide accordingly.
=> Updates Contrib Guide

api/v1alpha1/contour_types.go, config/crd/bases/operator.projectcontour.io_contours.yaml, examples/operator/operator.yaml, internal/equality/equality.go, internal/equality/equality_test.go, internal/object/object.go, internal/operator/controller/contour/cluster_role.go, internal/operator/controller/contour/cluster_role_binding.go, internal/operator/controller/contour/cluster_role_binding_test.go, internal/operator/controller/contour/cluster_role_test.go, internal/operator/controller/contour/configmap.go, internal/operator/controller/contour/controller.go, internal/operator/controller/contour/controller_test.go, internal/operator/controller/contour/daemonset.go, internal/operator/controller/contour/deployment.go, internal/operator/controller/contour/deployment_test.go, internal/operator/controller/contour/job.go, internal/operator/controller/contour/namespace.go, internal/operator/controller/contour/namespace_test.go, internal/operator/controller/contour/rbac.go, internal/operator/controller/contour/role.go, internal/operator/controller/contour/role_binding.go, internal/operator/controller/contour/role_binding_test.go, internal/operator/controller/contour/role_test.go, internal/operator/controller/contour/service.go, internal/operator/controller/contour/service_account.go
Previously, the operator would manage resources that matched a `Contour` even when the resources were provisioned by other mechanisms, i.e. `kubectl apply -f https://projectcontour.io/quickstart/contour.yaml`. This PR:
- Ensures only resources that include the `Contour` owner label are managed by the operator.
- Decomposes RBAC resource management into separate `<resource>.go` files.
- Adds unit tests for RBAC and Namespace resources.
- Updates the RBAC and Namespace resource management model from Create/Delete to Create/Update/Delete, providing management consistency other resources, i.e. DaemonSet.
- Updates the Job naming scheme to include the Contour version.
Requires: https://github.com/projectcontour/contour-operator/pull/173
Partially fixes: …
=> Adds Contour Owner Label to All Resources

config/rbac/role.yaml, internal/operator/controller/contour/controller.go
https://github.com/projectcontour/contour-operator/pull/177 added `BakendPolicy` to the operand's RBAC policies, but did not update the operator's RBAC policies. This causes the following error:
```
2021-02-01T19:53:43.522Z	ERROR	controller	Reconciler error	{"controller": "contour_controller", "name": "test-default-contour", "namespace": "contour-operator", "error": "failed to ensure rbac for contour contour-operator/test-default-contour: failed to ensure cluster role contour: failed to create cluster role contour: failed to create cluster role contour: clusterroles.rbac.authorization.k8s.io \"contour\" is forbidden: user \"system:serviceaccount:contour-operator:default\" (groups=[\"system:serviceaccounts\" \"system:serviceaccounts:contour-operator\" \"system:authenticated\"]) is …
```
=> Updates Operator RBAC for BackendPolicy

README.md
Updates the readme introduction to provide additional background on the operator.
xref: https://kubernetes.slack.com/archives/C8XRH2R4J/p1612283957080800
=> Updates the Readme Introduction

internal/operator/controller/contour/service.go
Fixes an issue where the incorrect equality check was being used for the two supported network publishing types.
=> Fixes Envoy Service Equality Check

api/v1alpha1/contour_types.go, config/crd/bases/operator.projectcontour.io_contours.yaml, examples/operator/operator.yaml, internal/operator/controller/contour/controller.go, internal/operator/scheme.go, internal/operator/suite_test.go
Implements `GatewayClassRef` in support of Gateway API. The contour controller will only instantiate a Contour environment if "None" is defined for `GatewayClassRef` or if the field is undefined (defaults to "None"). The "None" value signifies that a GatewayClass is not responsible for managing the Contour custom resource.
Requires: https://github.com/projectcontour/contour-operator/pull/180
xref: https://github.com/projectcontour/contour-operator/pull/171
=> Implements GatewayClassRef in Support of Gateway API

internal/equality/equality_test.go, internal/operator/config/config.go, internal/operator/controller/contour/service.go, internal/operator/controller/contour/service_test.go, internal/parse/parse.go, internal/parse/parse_test.go, test/e2e/operator_test.go, test/e2e/utils.go
Updates the e2e tests to:
1. Test the "LoadBalancerService" network publishing type. __Note:__ This is the default type of a Contour.
2. Adds a step to each e2e test that parses the operator's logs for error messages.
Requires: https://github.com/projectcontour/contour-operator/pull/193
Fixes: https://github.com/projectcontour/contour-operator/issues/191
=> Updates e2e Tests

internal/operator/controller/contour/controller.go
Updates controller logic to only validate a `Contour` for create/updates.
Fixes: https://github.com/projectcontour/contour-operator/issues/201
=> Updates Contour Validation

.github/workflows/prbuild.yaml
Runs the tests hourly against `contour:main`. Will see if this works, then need to add some sort of notification mechanism. 
=> ci: run tests each hour

.github/workflows/prbuild.yaml, Dockerfile, docs/CONTRIBUTING.md
Release notes: https://golang.org/doc/go1.16
=> Bump go to 1.16.0

examples/gateway/kuard/kuard.yaml
Updates httproute in kuard example to use `local.projectcontour.io` hostname.
xref: https://github.com/projectcontour/contour/pull/3394#discussion_r581467844
=> Updates HTTPRoute in Kuard Example

hack/test-example.sh, internal/objects/gateway/gateway.go, internal/objects/gatewayclass/finalizer.go, internal/objects/gatewayclass/gatewayclass.go, internal/operator/controller/contour/controller.go, internal/operator/controller/gateway/controller.go
Manages finalizers for dependent resources, i.e. Contour, of a Gateway. Ensures the finalizers are only removed when no other gateways reference the dependent resources.
Fixes https://github.com/projectcontour/contour-operator/issues/213
=> Finalizes Gateway Dependent Resources

examples/gateway/gateway-nodeport.yaml, examples/gateway/gateway.yaml
HTTPSRoute does not exist as per [gateway API docs](https://gateway-api.sigs.k8s.io/spec/#networking.x-k8s.io/v1alpha1.HTTPRoute).
For HTTPS protocol, `HTTPRoute` + `spec.tls` needs to be used.
/cc @danehans
=> Fix non-existent HTTPSRoute

examples/gateway/gateway-nodeport.yaml, examples/gateway/gateway.yaml
HTTPSRoute does not exist as per [gateway API
docs](https://gateway-api.sigs.k8s.io/spec/#networking.x-k8s.io/v1alpha1.HTTPRoute).
For HTTPS protocol, `HTTPRoute` + `spec.tls` needs to be used.
=> v1.13.1 cherrypicks

internal/objects/deployment/deployment_test.go
We were re-finding the contour container when we already had a reference
to it.
=> internal/objects/deployment: Simplify test

test/e2e/operator_test.go, test/e2e/utils.go
The Gateway e2e test is failing due to the following issues:
- The previous test was creating a gateway named "test-gateway-gateway" and in namespace "test-gateway-ns". Until https://github.com/projectcontour/contour-operator/issues/241 is fixed, the gateway must be projectcontour/contour.
- The gateway's route binding selector was unspecified, instead of specifying `HTTPRoute`.
=> Fixes Gateway e2e Test

test/e2e/operator_test.go
Adds info-level logging to e2e tests for contour/namespace delete operations.
=> Improves e2e Logging

api/v1alpha1/contour_types.go, config/crd/bases/operator.projectcontour.io_contours.yaml, examples/contour/contour-clusterip.yaml, examples/operator/operator.yaml, internal/objects/service/service.go, internal/objects/service/service_test.go, internal/operator/controller/contour/controller.go, internal/parse/parse.go, test/e2e/operator_test.go, test/e2e/utils.go
Adds support for the "ClusterIPService" Envoy network publishing type. This publishing type will expose Envoy pods as a Kubernetes service of type ClusterIP.
xref: https://github.com/projectcontour/contour-operator/issues/228
xref: https://docs.google.com/presentation/d/1sSffY27jcoK6UGdHqw03rDB4QifsTNWYa3LnCsMv3QU/edit?usp=sharing
cc: @nak3 
=> Adds ClusterIPService Network Publishing Type

.github/workflows/prbuild.yaml, Dockerfile
Release notes: https://golang.org/doc/devel/release.html#go1.16.minor
=> Bump go to 1.16.2

Makefile, config/manager/kustomization.yaml, config/manager/manager.yaml, examples/operator/operator.yaml, hack/release/make-release-tag.sh, hack/reset-image.sh, hack/verify-image.sh
Now that the operator contains a [config pkg](https://github.com/projectcontour/contour-operator/blob/main/internal/operator/config/config.go), these commandline flags should no longer be set. This will allow a single location to manage the default Envoy image.
=> Removes Unneeded Contour/Envoy Image Flags

internal/operator/controller/gateway/controller.go
Removes namespace deletion from the gateway controller. Unlike the Contour API, the Gateway API does not manage operands, i.e. Contour Deployment, in a separate namespace. Therefore, the gateway controller should not delete the namespace of the gateway.
Fixes https://github.com/projectcontour/contour-operator/issues/260
=> Removes Namespace Deletion from Gateway Controller

test/e2e/operator_test.go, test/e2e/utils.go
This patch fixes go fmt by:
```
go fmt ./test/e2e/*.go
```
=> Fix go format in test/e2e/*.go

internal/operator/status/status.go
When Contour CR has `gatewayClassRef` setting, `availableContours` and
`availableEnvoys` in status field are always `0`.
```
apiVersion: operator.projectcontour.io/v1alpha1
kind: Contour
...
status:
availableContours: 0
availableEnvoys: 0
```
This patch changes it to update the status regardless gatewayClassRef.
/cc @danehans 
Fixes https://github.com/projectcontour/contour-operator/issues/268
=> Update the status of availableContours and availableEnvoys regardless gatewayClassRef

internal/operator/status/status.go, test/e2e/utils.go
https://github.com/projectcontour/contour-operator/commit/45982221e1149074fb58753461903397115f926d bumped the linter. The New linter has caught a few issue that now cause the make `check` target to fail. This PR fixes these errors.
=> Fixes Linter Errors

internal/objects/contour/contour.go, internal/objects/rbac.go, test/e2e/operator_test.go
`OtherContoursExistInSpecNs()`: Ensures the contour from the list is not the same as the `contour` parameter before comparing `spec.namespace.name` .  Fixes https://github.com/projectcontour/contour-operator/issues/281
Manages cluster-scoped RBAC resources on a per-Contour basis. Adds an e2e to test the multi-Contour use case. Fixes https://github.com/projectcontour/contour-operator/issues/280
=> Includes Contour Namespace in Cluster RBAC Resources

internal/operator/controller/contour/controller.go, pkg/validation/validation.go, pkg/validation/validation_test.go
Until https://github.com/projectcontour/contour-operator/issues/18 is fixed, only one Contour is allowed per namespace. This PR verifies no other Contour has been provisioned in `spec.namespace.name` before ensuring a `Contour`.
Fixes https://github.com/projectcontour/contour-operator/issues/255
=> Enforces One Contour Per Namespace

cmd/contour-operator.go, config/rbac/role.yaml, examples/operator/operator.yaml, internal/operator/operator.go, internal/operator/scheme.go, internal/operator/suite_test.go
Adds gateway/gatewayclass controllers if the operator is started and Gateway CRDs exist (not including UDPRoute/TCPRoute). Note that the operator will fail to start if the necessary Gateway CRDs are not installed in the cluster.
Fixes #221 
=> Conditionally Starts Gateway Controllers

internal/objects/gateway/gateway.go, internal/operator/controller/contour/controller.go, internal/operator/controller/gateway/controller.go, internal/operator/controller/gatewayclass/controller.go, test/e2e/operator_test.go, test/e2e/utils.go
The Gateway API uses the [controller field](https://gateway-api.sigs.k8s.io/spec/#networking.x-k8s.io/v1alpha1.GatewayClassSpec), to indicate resource ownership. This PR adds a predicate to gatewayclass/gateway controllers to ensure only Gateway resources that are owned by the operator are reconciled.
Fixes https://github.com/projectcontour/contour-operator/issues/284
=> Ensures Owned Gateway Resources are Reconciled

test/e2e/operator_test.go
Current test uses ContainersReady to wait for pod condition but
PodReady makes sure the condition more strictly.
ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-conditions
=> Use PodReady rather than ContainersReady in e2e

test/e2e/utils.go
This patch cleans up utils.go by deleting unnecessary lines.
=> Clean up test utils

internal/operator/controller/contour/controller.go, test/e2e/operator_test.go, test/e2e/utils.go
operator does not clean up envoy service when envoy
is ClusterIPService type.
This patch fixes it.
Fixes https://github.com/projectcontour/contour-operator/issues/290
=> Clean up envoy service when ClusterIPService type

internal/operator/controller/gateway/controller.go, test/e2e/operator_test.go
operator does not create envoy service when envoy
is ClusterIPService type and gatewayClassRef.
This patch fixes it.
Fix https://github.com/projectcontour/contour-operator/issues/291
=> Create envoy service with ClusterIPService type and gatewayClassRef

internal/objects/contour/contour.go, internal/objects/deployment/deployment.go, test/e2e/operator_test.go, test/e2e/utils.go
This patch changes to update deployment when contour deployment has the
correct owner labels.
Fix https://github.com/projectcontour/contour-operator/issues/298
__caveat:__ If Contour CR has a `gatewayClassRef`setting, the issue still exists due to another reason.
/cc @danehans @eplightning
=> Update Deployment when owner labels exist

internal/operator/suite_test.go
Re-gets Contour before attempting to update it, to avoid having a
stale in-memory version that can't be updated. Fixes a test flake.
=> internal/operator tests: re-get Contour before updating

config/rbac/role.yaml, examples/operator/operator.yaml, internal/objects/clusterrole/cluster_role.go, internal/operator/operator.go
Updates RBAC to support TCPRoute and UDPRoute types.
Fixes #303
=> Updates RBAC for TCP/UDPRoute Types

test/e2e/operator_test.go
Fixes some inaccurate log statements. Also fixes a bug where
the default namespace for Contours was being inadvertently
reassigned during the two-Contour test, impacting other tests.
=> test/e2e: fix logging and namespace assignment

test/e2e/operator_test.go, test/e2e/utils.go
This patch adds check for available envoys and contours during e2e
test.
Fix https://github.com/projectcontour/contour-operator/issues/271
/cc  @danehans @sunjayBhatia
=> Add e2e tests check for available Envoys and Contours

examples/gateway/gateway-nodeport.yaml, examples/gateway/gateway.yaml
Removes namespace "contour-operator" from the gateway examples. Defining this namespace is unneeded since it's defined in the example operator manifest. Including this namespace in the gateway examples will cause the operator to be deleted when either of the gateway examples are deleted.
=> Updates Examples Namespace

hack/kind-dev-cluster.sh
https://github.com/projectcontour/contour-operator/pull/328 bumped CI to support k8s v1.21. This PR bumps the kind node image to match.
=> Updates Kind Node Image

.github/workflows/prbuild.yaml
=> CI: run e2e tests against all supported Kubernetes versions

.github/workflows/prbuild.yaml, Dockerfile
See release notes:
https://golang.org/doc/devel/release.html#go1.16.minor
=> Bump go to 1.16.4

.github/workflows/verify_manifests_main.yaml, Makefile, hack/load-image.sh, hack/reset-image.sh, test/e2e/operator_test.go
CI jobs were previously failing when run as part of PRs or
push builds against any release branches, because the image
tags in the YAML files were not "main", but rather a specific
release version.
Moves manifest image verification of "main" tag pull policy to
a separate workflow that runs only on PRs and pushes to main.
Also modifies load-image.sh and reset-image.sh to replace any
existing image tag in the manifest with the desired tag. Also
fixes E2E upgrade tests to look for the correct Contour image
tag.
Closes #169.
Closes #289.
=> CI: fix issues causing failures on release branches

examples/gateway/gateway-nodeport.yaml, examples/gateway/gateway.yaml, internal/operator/controller/gateway/controller.go, pkg/validation/validation.go, pkg/validation/validation_test.go, test/e2e/utils.go
-`internal/operator/controller/gateway/controller.go`: Moves validation before checking finalizer of gateway (provides consistency with other controllers). `EnsureGateway` now takes a `Contour` as a parameter since contour<>gateway validation is now fully handled by the validation pkg.
- `pkg/validation/validation.go`: Adds `gatewayContour()` used to validate the contour<>gateway association. Adds a check to ensure `contour.spec.namespace.name` = `gateway.namespace`.
Fixes #344 
=> Improves Gateway Validation

internal/objects/daemonset/daemonset.go, internal/objects/deployment/deployment.go
Removes the "app.kubernetes.io/version" label from the Contour/Envoy operand objects.
Fixes: https://github.com/projectcontour/contour-operator/issues/363
=> Removes Version Label

pkg/validation/validation.go, pkg/validation/validation_test.go
Updates `validation.Gateway()` to immediately return an error if the GatewayClss status is not "Admitted=True".
Fixes #337 
=> Fixes Gateway Validation Panic

internal/objects/service/service.go, internal/objects/service/service_test.go
Adds support for managing the [proxy protocol](https://kubernetes.io/docs/concepts/services-networking/service/#proxy-protocol-support-on-aws) for AWS Classic load balancers.
Requires: https://github.com/projectcontour/contour-operator/pull/366
Fixes: https://github.com/projectcontour/contour-operator/issues/49
xref: https://projectcontour.io/guides/proxy-proto/
=> Adds Proxy Protocol Support

internal/objects/service/service_test.go
Refactors to check each Envoy service for an exact set
of annotation keys, rather than checking for the existence
and non-existence of a subset of annotations.
=> internal/objects/service: refactor test

config/default/manager_auth_proxy_patch.yaml, examples/operator/operator.yaml
This is addressing #375.
Contour and Envoy are supported on arm64 and do publish multi-arch images.
The contour-operator does leverage `kube-rbac-proxy` image `v0.5.0` published by kubebuilder project. 
These images are not multi-arch.
The `kube-rbac-proxy` project does publish to `quay.io/brancz/kube-rbac-proxy` and these images are build for multi-arch since `v0.6.0`.
This PR also use latest `v0.10.0`, which is now based on `gcr.io/distroless/static` and running nonroot
=> update kube-rbac-proxy image version to support arm64

.github/workflows/prbuild.yaml, examples/operator/operator.yaml, hack/actions/check-uncommitted-codegen.sh
Adds a CI check that runs all code generation Make tasks
and then errors if there are any uncommitted changes,
meaning the PR should've updated generated code but did
not.
Closes #384.
=> CI: add uncommitted codegen check

.github/workflows/prbuild.yaml, Dockerfile
See release notes: https://golang.org/doc/devel/release#go1.16.minor
=> Bump golang to 1.16.5

internal/objects/configmap/configmap.go, internal/objects/configmap/configmap_test.go, internal/objects/gateway/gateway.go, internal/operator/controller/contour/controller.go, internal/operator/controller/gateway/controller.go, internal/operator/controller/gatewayclass/controller.go, internal/operator/status/conditions.go, internal/operator/status/conditions_test.go, internal/operator/status/status.go, pkg/validation/validation.go, pkg/validation/validation_test.go, test/e2e/operator_test.go, test/e2e/utils.go
Now that Contour reconciles and sets status on GatewayClass and Gateway
resources, this is the first step to clean up the operator to remove
bits that conflict with Contour itself.
- Pass controller name string to Contour in ConfigMap to ensure Contour
is properly configured for Gateway API
- Remove status updating/checking on Gateway API resources
- Don't set GatewayClass status or expect it to be admitted by
Operator
- Don't set Gateway status or expect it to be set in tests
- When reconciling Contour CRD, do not check if referenced
GatewayClass is admitted
- Adds test to make sure multiple Contours with Gateway API work
- Currently this is a bit broken and not how Gateway API *should* work
- Due to the fact that the Operator only reconciles 1 GatewayClass and passes that along to …
=> Fixes for Contour now reconciling GatewayClasses and Gateways

pkg/validation/validation.go, pkg/validation/validation_test.go
This reverts commit 892c8c17bf0a066ea657b847bd65819f2d2e0117.
Fixes: https://github.com/projectcontour/contour-operator/issues/403
=> Revert "Adds IngressClassName Validation (#388)"

test/e2e/operator_test.go, test/e2e/utils.go
Also use timeout specificly for waiting for Contour, not general timeout
Fixes: #415
=> Use longer timeout to wait for Contour status

.github/workflows/prbuild.yaml, hack/test-example.sh
In test-example, deletes Gateway API resources in the expected
order to avoid race conditions with finalizers that lead to
test flakes. Also adds a 30-minute timeout to the GitHub Actions
job.
=> fixes for test-example

test/e2e/utils.go
Adds a 5-second timeout to the HTTP client to prevent
requests from hanging forever. Requests are wrapped in
a retry loop so timed-out requests will be retried.
=> test/e2e: add a timeout to HTTP client

api/v1alpha1/contour_types.go, api/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/operator.projectcontour.io_contours.yaml, examples/operator/operator.yaml
- add field we need for properly configuring Contour when we remove
Gateway API controllers from Operator
- once we start using it, mark GatewayClassRef as deprecated
- GatewayClassRef can be removed in a future API revision/in Contour
config CRD when that comes about
=> Add GatewayControllerName field to Contour CRD

examples/gateway/gateway-nodeport.yaml, hack/test-example.sh
Also refactor so both tests actually have to pass not just the second
one
Fixes: #419
=> Add time limit to example test curl

internal/objects/configmap/configmap.go, internal/objects/configmap/configmap_test.go
Contour operator creates configmap with the strange `contour.yaml: |2` as below:
```
$ kubectl get cm -n projectcontour contour -o yaml
apiVersion: v1
data:
contour.yaml: |2
#
```
Actually `|2` is valid yaml but it makes confused.
This patch fixes it.
=> Remove strange number `|2` in configmap

.github/workflows/build_main.yaml, .github/workflows/build_tag.yaml, Makefile, docs/CONTRIBUTING.md
Starts pushing container images to GHCR in
addition to Docker Hub. Images will be pushed
to both registries for a period of time, until
the Docker Hub push is removed.
=> Push images to GHCR and Docker Hub in parallel

internal/objects/clusterrole/cluster_role.go, internal/operator/operator.go
The upcoming v1alpha2 release of Gateway API drops
BackendPolicy. Contour has dropped references to it
in 7013489dac80e71b2373240a83fe451162f4a4c5. This PR
removes RBAC setup for it from the operator.
=> remove BackendPolicy RBAC

test/e2e/example/example_test.go, test/e2e/operator_test.go, test/e2e/utils.go
use e2e package delete function that stops waiting once namespace is terminating
=> Fix example test namespace deletion

.github/workflows/build_main.yaml, .github/workflows/build_tag.yaml, Makefile, config/manager/manager.yaml, docs/CONTRIBUTING.md, examples/operator/operator.yaml, hack/release/make-release-tag.sh, hack/verify-image.sh, internal/config/config.go, test/e2e/operator_test.go
Updates examples, CI and docs to use
the GHCR image by default. The Docker
Hub image will continue to be pushed
for the time being to help migration.
=> use GHCR image by default

Makefile
So we don't run them many times in the CI pipelines
=> Don't run unit tests when building container image

.github/workflows/prbuild.yaml
=> Use go download cache in e2e job

config/crd/contour/01-crds.yaml, config/rbac/role.yaml, examples/operator/operator.yaml, internal/objects/clusterrole/cluster_role.go, internal/operator/operator.go
Updates operator per Contour changes:
https://github.com/projectcontour/contour/pull/4141
https://github.com/projectcontour/contour/pull/4138
https://github.com/projectcontour/contour/pull/4145
=> get operator in sync with Contour

examples/contour/contour-nodeport.yaml, test/e2e/example/example_test.go
Puts the Contour CR for the NodePort
examples into the default namespace
to be consistent with other examples.
(This helps with updating the getting started guide, in https://github.com/projectcontour/contour/pull/4288).
=> examples: move NodePort example to default namespace

hack/actions/build-and-push-release-images.sh
Adds `--force` to `git fetch --tags` to
work with the v2 checkout action.
=> hack/actions: fix tag fetching in release workflow

.github/workflows/build_main.yaml, .github/workflows/build_tag.yaml
Removes the Docker Hub image push since
images are now published on GHCR.
=> stop pushing images to Docker Hub

cmd/contour-operator.go, hack/release/make-release-tag.sh, internal/controller/controller.go, internal/objects/daemonset/daemonset_test.go, internal/objects/deployment/deployment_test.go, internal/objects/job/job.go, internal/objects/job/job_test.go, internal/operator/config.go, internal/operator/operator.go, internal/operator/operator_test.go, test/e2e/operator_test.go
Drops the internal/config package and moves the
Config struct into internal/operator where it's
used.
=> move Config type into internal/operator

internal/objects/clusterrole/cluster_role.go, internal/objects/clusterrolebinding/cluster_role_binding.go, internal/objects/daemonset/daemonset.go, internal/objects/deployment/deployment.go, internal/objects/job/job.go, internal/objects/namespace/namespace.go, internal/objects/role/role.go, internal/objects/rolebinding/role_binding.go, internal/objects/service/service.go, internal/objects/serviceaccount/service_account.go
Uses the OwnerLabels helper function to set labels
for all created resources.
=> internal/objects: use OwnerLabels helper everywhere

.github/workflows/prbuild.yaml, Dockerfile, hack/golangci-lint.sh
Updates to Go 1.18. Also updates golangci-lint
to v1.45 for Go 1.18 support.
=> update to Go 1.18

internal/objects/job/job.go, internal/objects/job/job_test.go
Signed-off-by: Javier Salmeron Garcia <jsalmeron@vmware.com>
Fixes https://github.com/projectcontour/contour-operator/issues/524
This PR truncates the certgen job name to 63 characters, and adds a validation test to ensure it works as expected.
=> fix: :bug: Truncate certgen job name to 63 characters

config/rbac/role.yaml, examples/operator/operator.yaml, internal/objects/clusterrole/cluster_role.go, internal/operator/operator.go
Adds RBAC rules for ReferenceGrant.
=> Gateway API: add ReferenceGrant RBAC

.github/workflows/prbuild.yaml
Changes the schedule for running the build
and test workflow to once per day since we
no longer need it to run hourly.
=> change build and test schedule to once per day

.github/workflows/prbuild.yaml, Dockerfile
See release notes: https://go.dev/doc/devel/release#go1.19.minor
=> Bump golang to 1.19.2

.github/workflows/prbuild.yaml
=> ignore dependabot branches for push builds

config/crd/gateway/01-crds.yaml, config/rbac/role.yaml, examples/operator/operator.yaml, go.mod, go.sum, internal/objects/clusterrole/cluster_role.go, internal/operator/operator.go, internal/operator/scheme.go, test/e2e/example/example_test.go, test/e2e/utils.go
Fixes RBAC etc. and bumps go.mod dependency
=> Updates for Gateway API 0.6.0-rc1

config/crd/contour/01-crds.yaml, examples/operator/operator.yaml, internal/operator/operator_test.go
=> sync CRDs from projectcontour/contour

.github/workflows/prbuild.yaml, hack/actions/install-kubernetes-toolchain.sh
Tested versions are now 1.24, 1.25, 1.26.
=> update Kubernetes versions
